In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn. preprocessing import LabelEncoder, StandardScaler, OneHotEncoder

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

# Train-Test Split

In [8]:
X_train, X_test,y_train, y_test= train_test_split(X,y, test_size=0.2)

# Scaling

In [9]:
scaler=StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
print(X_train)

[[-0.94016311  0.46344068 -0.97636663 ... -1.74182034 -0.7437282
  -1.02645235]
 [-1.2505962  -0.55428063 -1.22594652 ... -0.93004946 -0.62174724
   0.05604757]
 [-0.1490317   0.86010266 -0.20063411 ... -0.65002351 -0.44446824
  -0.81814613]
 ...
 [ 1.84312894 -0.37748272  1.69758503 ...  1.08887676 -0.26881566
   0.30647665]
 [ 0.61056912  0.28890941  0.61787167 ...  0.66731595  0.30530807
  -0.09859528]
 [ 1.71700654  1.99795588  1.62698839 ...  0.73580056 -0.55831714
  -1.0004862 ]]


In [11]:
print(y_train)

550    B
110    B
545    B
43     M
436    B
      ..
244    M
567    M
1      M
328    M
565    M
Name: diagnosis, Length: 455, dtype: object


# Label Encoding

In [12]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,

# Numpy to PyTorch

In [14]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [15]:
X_train_tensor

tensor([[-0.9402,  0.4634, -0.9764,  ..., -1.7418, -0.7437, -1.0265],
        [-1.2506, -0.5543, -1.2259,  ..., -0.9300, -0.6217,  0.0560],
        [-0.1490,  0.8601, -0.2006,  ..., -0.6500, -0.4445, -0.8181],
        ...,
        [ 1.8431, -0.3775,  1.6976,  ...,  1.0889, -0.2688,  0.3065],
        [ 0.6106,  0.2889,  0.6179,  ...,  0.6673,  0.3053, -0.0986],
        [ 1.7170,  1.9980,  1.6270,  ...,  0.7358, -0.5583, -1.0005]],
       dtype=torch.float64)

In [16]:
X_train_tensor.shape

torch.Size([455, 30])

In [17]:
y_train_tensor.shape

torch.Size([455])

# Define the model

In [18]:
class MyneuralNN():
    def __init__(self, X):
        self.weights=torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64, requires_grad=True)
        
    def forward (self, X):
        z=torch.matmul(X, self.weights)+self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function( self, y_pred, y):
        #clamp prediction to avoid log(0)
        epsilon=1e-7
        y_pred=torch.clamp(y_pred, epsilon, 1-epsilon)
        
        #Calculate loss
        loss=-(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
        return loss

In [19]:
learning_rate=0.1
epochs=25

# Training Pipline

In [20]:
#creating model
model=MyneuralNN(X_train_tensor)


#define loop
for epoch in range(epochs):
#forward pass
    y_pred=model.forward(X_train_tensor)
    #print(y_pred)
#loss calculate
    loss=model.loss_function(y_pred, y_train_tensor)
    
#backward pass
    loss.backward()
    
#parameters update
    with torch.no_grad():
        model.weights-=learning_rate*model.weights.grad
        model.bias-=learning_rate*model.bias.grad
    
#zero gradients
    model.weights.grad.zero_()
    model.weights.grad.zero_()
    
#print loss in each epoch
    print(f'Epoch:{epoch+1}, Loss : {loss.item()}')

Epoch:1, Loss : 3.984441582550918
Epoch:2, Loss : 3.874075103141417
Epoch:3, Loss : 3.7587946398993024
Epoch:4, Loss : 3.636332386815238
Epoch:5, Loss : 3.508084276120031
Epoch:6, Loss : 3.375260212171333
Epoch:7, Loss : 3.232287618823222
Epoch:8, Loss : 3.0832034121221596
Epoch:9, Loss : 2.9343022552428693
Epoch:10, Loss : 2.778792414124811
Epoch:11, Loss : 2.6143680519216534
Epoch:12, Loss : 2.450418343413004
Epoch:13, Loss : 2.2863631439301018
Epoch:14, Loss : 2.123407167395302
Epoch:15, Loss : 1.9622471138355555
Epoch:16, Loss : 1.8010233031510556
Epoch:17, Loss : 1.6434905700687434
Epoch:18, Loss : 1.4943783829494368
Epoch:19, Loss : 1.3553369919147864
Epoch:20, Loss : 1.2309203445748125
Epoch:21, Loss : 1.1231859233849266
Epoch:22, Loss : 1.0336630478808602
Epoch:23, Loss : 0.9625953946598621
Epoch:24, Loss : 0.9085706195225797
Epoch:25, Loss : 0.8689570827030862


In [21]:
model.weights

tensor([[ 0.4354],
        [ 0.4759],
        [ 0.3045],
        [-0.2509],
        [ 0.4609],
        [-0.3341],
        [-0.2764],
        [-0.4074],
        [-0.0565],
        [ 0.0880],
        [ 0.0713],
        [ 0.4485],
        [ 0.1417],
        [ 0.0578],
        [-0.2337],
        [-0.0955],
        [ 0.3235],
        [ 0.1644],
        [ 0.5311],
        [ 0.2932],
        [-0.3171],
        [ 0.0044],
        [ 0.4197],
        [-0.2404],
        [ 0.3088],
        [-0.1569],
        [-0.3048],
        [ 0.1339],
        [ 0.1476],
        [ 0.3523]], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias

tensor([-0.7590], dtype=torch.float64, requires_grad=True)

# Evaluation

In [23]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.9).float()
    
    accuracy=(y_pred==y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.632964015007019
